GoogleCloudPlatform/firebase-extensions

storage-label-videos/README.md, storage-transcode-videos/README.md
Fix install links and images
FYI the extension isn't published yet so the install link's not working
=> Fix install links

.github/workflows/validate.yaml, package-lock.json, package.json
Note: tests run when ran within their own project folders
=> chore: update ci, remove test and add formatting script in package json

storage-reverse-image-search/functions/src/functions/backfill_task.ts, storage-reverse-image-search/functions/src/functions/create_index_trigger.ts
=> fix(storage-reverse-image-search): backfill failing to create metdata doc thus index

firestore-semantic-search/extension.yaml, firestore-semantic-search/functions/src/common/vertex.ts, firestore-semantic-search/functions/src/functions/backfill_trigger.ts, firestore-semantic-search/functions/src/functions/datapoint_write_task.ts, firestore-semantic-search/functions/src/functions/stream_remove_datapoint.ts, firestore-semantic-search/functions/src/functions/stream_update_datapoint.ts, storage-reverse-image-search/extension.yaml, storage-reverse-image-search/functions/src/common/vertex.ts, storage-reverse-image-search/functions/src/config.ts, storage-reverse-image-search/functions/src/functions/backfill_trigger.ts, storage-reverse-image-search/functions/src/functions/create_index_trigger.ts, storage-reverse-image-search/functions/src/functions/datapoint_write_task.ts, storage-reverse-image-search/functions/src/functions/stream_remove_datapoint.ts, storage-reverse-image-search/functions/src/functions/stream_update_datapoint.ts
Support optional backfill in Reverse Image Search & Semantic Text Search.
=> feat(vertex-extensions): optional backfill 

storage-label-images/PREINSTALL.md
Correct the description of where the output is written, and add a code sample of how to find the result.
Fixes https://github.com/GoogleCloudPlatform/firebase-extensions/issues/43
=> Update PREINSTALL.md for storage-label-images

.github/workflows/readmes-updated.yaml, .gitignore, bigquery-firestore-export/README.md, firestore-palm-chatbot/README.md, firestore-palm-gen-text/README.md, firestore-palm-summarize-text/README.md, firestore-semantic-search/README.md, palm-secure-backend/README.md, storage-label-videos/README.md, storage-reverse-image-search/README.md, storage-transcode-videos/README.md, storage-transcode-videos/functions/package.json
adds a workflow to check if readmes are generated
=> chore(*): add generate README CI

.github/workflows/readmes-updated.yaml
Make this workflow trigger on pushes and PRs to next
=> chore(*): make readme CI trigger on next branch

firestore-palm-chatbot/PREINSTALL.md, firestore-palm-chatbot/README.md, firestore-palm-chatbot/functions/src/index.ts, firestore-palm-gen-text/PREINSTALL.md, firestore-palm-gen-text/README.md, firestore-palm-gen-text/functions/src/index.ts, firestore-palm-summarize-text/PREINSTALL.md, firestore-palm-summarize-text/README.md, firestore-palm-summarize-text/functions/src/index.ts
fixes https://github.com/GoogleCloudPlatform/firebase-extensions/issues/42
=> feat(PaLM firestore extensions): add REGENERATE functionality

firestore-semantic-search/CHANGELOG.md
Preparing for a 1.5.0 release.
=> chore(firestore-semantic-search): update CHANGELOG for release

firestore-palm-chatbot/PREINSTALL.md, firestore-palm-chatbot/README.md, firestore-palm-gen-text/CHANGELOG.md, firestore-palm-gen-text/PREINSTALL.md, firestore-palm-gen-text/README.md, firestore-palm-gen-text/extension.yaml, firestore-palm-gen-text/functions/src/index.ts, firestore-palm-summarize-text/CHANGELOG.md, firestore-palm-summarize-text/PREINSTALL.md, firestore-palm-summarize-text/README.md, firestore-palm-summarize-text/extension.yaml, firestore-palm-summarize-text/functions/src/index.ts
- fix flawed logic
- update versions and docs
=> fix(*): fix regen functionality for PaLM

firestore-palm-chatbot/functions/src/index.ts, firestore-palm-gen-text/functions/src/index.ts, firestore-palm-summarize-text/functions/src/index.ts
fixes bug where the ERROR update retriggers the function and retries in a loop
=> fix(*): fix PaLM loop bug

palm-secure-backend/POSTINSTALL.md
=> docs(palm-secure-backend): update code sample links in docs

firestore-palm-chatbot/extension.yaml, firestore-palm-gen-text/extension.yaml, firestore-palm-summarize-text/extension.yaml
fixes https://github.com/GoogleCloudPlatform/firebase-extensions/issues/95
=> fix: add validation to COLLECTION_NAME params

storage-reverse-image-search/README.md, storage-reverse-image-search/extension.yaml
in place of https://github.com/GoogleCloudPlatform/firebase-extensions/pull/78
=> @invertase/typo

firestore-palm-chatbot/README.md, firestore-palm-chatbot/extension.yaml, firestore-palm-gen-text/README.md, firestore-palm-gen-text/extension.yaml, firestore-palm-summarize-text/README.md, firestore-palm-summarize-text/extension.yaml
This PR improves the explanation of new params
=> docs: update palm param docs

bigquery-firestore-export/extension.yaml, firestore-palm-chatbot/extension.yaml, firestore-palm-gen-text/extension.yaml, firestore-semantic-search/extension.yaml, storage-extract-image-text/extension.yaml
=> fix(*): updated regex validation for collection paths

firestore-semantic-search/functions/src/common/palm_embeddings.ts
fixing endpoint according to: https://cloud.google.com/vertex-ai/docs/generative-ai/embeddings/get-text-embeddings#generative-ai-get-text-embedding-nodejs
=> fix(firestore-semantic-search): correct apiEndpoint

firestore-palm-chatbot/functions/package-lock.json, firestore-palm-chatbot/functions/package.json, firestore-palm-chatbot/functions/src/discussion.ts, firestore-palm-gen-text/functions/src/generator.ts, firestore-palm-gen-text/functions/src/index.ts, firestore-palm-summarize-text/functions/package-lock.json, firestore-palm-summarize-text/functions/package.json, firestore-palm-summarize-text/functions/src/generator.ts, firestore-palm-summarize-text/functions/src/index.ts
This PR adds handling for the content filters currently implemented on both GL and Vertex PaLM APIs
=> feat(*): handle content filters for both APIs

firestore-palm-chatbot/CHANGELOG.md, firestore-palm-gen-text/CHANGELOG.md, firestore-palm-gen-text/functions/src/generator.ts, firestore-palm-summarize-text/CHANGELOG.md
This PR removes a small bug where an error was thrown wrongly, and updates the CHANGELOGs
=> chore(*): update changelogs and small gen-text fix

firestore-palm-chatbot/functions/src/discussion.ts, firestore-palm-gen-text/functions/src/generator.ts, firestore-palm-summarize-text/CHANGELOG.md, firestore-palm-summarize-text/extension.yaml, firestore-palm-summarize-text/functions/src/generator.ts
This PR fixes a bug where apiEndpoint depended on location (location is fixed for this param)
=> fix(*): fix apiEndpoints location error

firestore-palm-chatbot/PREINSTALL.md, firestore-palm-chatbot/README.md, firestore-palm-gen-text/PREINSTALL.md, firestore-palm-gen-text/README.md, firestore-palm-summarize-text/PREINSTALL.md, firestore-palm-summarize-text/README.md, firestore-semantic-search/PREINSTALL.md, firestore-semantic-search/README.md
fixes: https://github.com/GoogleCloudPlatform/firebase-extensions/issues/157
=> docs: update palm provider docs

firestore-palm-summarize-text/functions/package-lock.json
bumped google-gax, protobufjs, word-wrap and tested it doesn't break things
closes https://github.com/GoogleCloudPlatform/firebase-extensions/pull/153 and https://github.com/GoogleCloudPlatform/firebase-extensions/pull/123
=> chore: bump summarize dependencies

firestore-palm-summarize-text/functions/src/config.ts, firestore-palm-summarize-text/functions/src/generator.ts, firestore-palm-summarize-text/functions/src/index.ts
This prompt should make hallucinations less likely
=> feat(firestore-palm-summarize-text): improve prompt

firestore-palm-chatbot/CHANGELOG.md, firestore-palm-chatbot/extension.yaml, firestore-palm-chatbot/functions/package-lock.json, firestore-palm-chatbot/functions/package.json
This PR bumps the PaLM dependencies and updates the changelog ready for release
=> chore(firestore-palm-chatbot): bump deps and update CHANGELOG

firestore-palm-summarize-text/CHANGELOG.md, firestore-palm-summarize-text/PREINSTALL.md, firestore-palm-summarize-text/README.md, firestore-palm-summarize-text/extension.yaml, firestore-palm-summarize-text/functions/package-lock.json, firestore-palm-summarize-text/functions/package.json, firestore-palm-summarize-text/functions/src/config.ts, firestore-palm-summarize-text/functions/src/generator.ts, firestore-palm-summarize-text/functions/src/index.ts, firestore-palm-summarize-text/functions/src/types.ts
This PR adds a parameter in for managing the content filters for summarize text
=> feat(firestore-palm-summarize-text): add content filter threshold param

speech-to-text/extension.yaml, speech-to-text/functions/src/config.ts, speech-to-text/functions/src/transcribe-audio.ts
This PR fixes https://github.com/GoogleCloudPlatform/firebase-extensions/issues/216
=> feat(speech-to-text): add automatic punctuation

firestore-incremental-capture/CHANGELOG.md, firestore-incremental-capture/PREINSTALL.md, firestore-incremental-capture/README.md, firestore-incremental-capture/extension.yaml, firestore-incremental-capture/functions/package.json
This PR updates the documentation of the extension
=> docs(firestore-incremental-capture): update documentation

storage-extract-image-text/PREINSTALL.md, storage-extract-image-text/README.md, storage-extract-image-text/extension.yaml
The Extract Image Text with Cloud Vision AI Doc doesn't follow the source code in some parts. I have now updated the doc to match the source code.
=> doc: improve Extract Image Text with Cloud Vision AI doc

firestore-semantic-search/CHANGELOG.md, firestore-semantic-search/extension.yaml, storage-reverse-image-search/CHANGELOG.md, storage-reverse-image-search/extension.yaml
Releasing the following extensions:
- firestore-semantic-search
- storage-reverse-image-search
=> release: 28 november 2023

storage-reverse-image-search/extension.yaml
=> chore(storage-reverse-image-search): add default values for model

firestore-genai-chatbot/CHANGELOG.md, firestore-genai-chatbot/PREINSTALL.md, firestore-genai-chatbot/README.md, firestore-genai-chatbot/extension.yaml, firestore-multimodal-genai/CHANGELOG.md, firestore-multimodal-genai/PREINSTALL.md, firestore-multimodal-genai/README.md, firestore-multimodal-genai/extension.yaml
This PR replaces ambiguous references to PaLM+Gemini with just Gemini references
=> docs(*): update gemini extension docs

firestore-genai-chatbot/CHANGELOG.md, firestore-genai-chatbot/PREINSTALL.md, firestore-genai-chatbot/README.md, firestore-genai-chatbot/extension.yaml, firestore-genai-chatbot/functions/package-lock.json, firestore-genai-chatbot/functions/package.json, firestore-genai-chatbot/functions/src/generative-client/generative_language.ts, firestore-genai-chatbot/functions/src/generative-client/index.ts, firestore-multimodal-genai/CHANGELOG.md, firestore-multimodal-genai/PREINSTALL.md, firestore-multimodal-genai/README.md, firestore-multimodal-genai/extension.yaml, firestore-multimodal-genai/functions/package-lock.json, firestore-multimodal-genai/functions/package.json, firestore-multimodal-genai/functions/src/generative-client/generate/generative_ai.ts, firestore-multimodal-genai/functions/src/generative-client/generate/generative_language.ts, firestore-multimodal-genai/functions/src/generative-client/generate/index.ts
This swaps out the SDK we're using, so that we support ADC auth
=> feat(*): add ADC to Gemini exts

firestore-genai-chatbot/CHANGELOG.md, firestore-genai-chatbot/extension.yaml, firestore-genai-chatbot/functions/src/config.ts, firestore-genai-chatbot/functions/src/generate_chat_response.ts, firestore-genai-chatbot/functions/src/generative-client/base_class.ts, firestore-genai-chatbot/functions/src/generative-client/generative_language.ts, firestore-genai-chatbot/functions/src/generative-client/google_ai.ts
This PR adds context as a feature to the Gemini chat
=> fix(firebase-genai-chatbot): allow context to work from an extension param

palm-secure-backend/POSTINSTALL.md
fixes https://github.com/GoogleCloudPlatform/firebase-extensions/issues/291
=> docs(palm-secure-backend):update the doc for POSTINSTALL.md

_emulator/extensions/firestore-palm-chatbot.env, firestore-palm-chatbot/functions/__tests__/generative/context.test.ts, firestore-palm-chatbot/functions/__tests__/generative/index.test.ts, firestore-palm-chatbot/functions/__tests__/vertex/context.test.ts, firestore-palm-chatbot/functions/__tests__/vertex/index.test.ts, firestore-palm-chatbot/functions/src/config.ts, firestore-palm-gen-text/extension.yaml, firestore-palm-gen-text/functions/__tests__/generative.test.ts, firestore-palm-gen-text/functions/__tests__/vertex.test.ts, firestore-palm-gen-text/functions/src/config.ts, firestore-palm-summarize-text/functions/__tests__/generative.test.ts, firestore-palm-summarize-text/functions/__tests__/vertex.test.ts, firestore-palm-summarize-text/functions/src/config.ts
=> feat(*): support latest PaLM models

bigquery-firestore-export/functions/src/helper.ts
This PR will fix https://github.com/GoogleCloudPlatform/firebase-extensions/issues/168
=> feat(bigquery-firestore-export): support missing datatypes

storage-reverse-image-search/functions/__tests__/functions/create_index_trigger.test.ts
This PR disables some flaky tests which are halting dev
=> chore(storage-reverse-image-search): disable flaky tests temporarily

firestore-genai-chatbot/README.md, firestore-genai-chatbot/extension.yaml, firestore-genai-chatbot/functions/__tests__/unit/overrides.test.ts, firestore-genai-chatbot/functions/src/config.ts, firestore-genai-chatbot/functions/src/generate_chat_response.ts, firestore-genai-chatbot/functions/src/generative-client/google_ai.ts, firestore-genai-chatbot/functions/src/overrides.ts, firestore-genai-chatbot/functions/src/types.ts
fixes https://github.com/GoogleCloudPlatform/firebase-extensions/issues/341
=> feat: support maxOutputTokens

firestore-multimodal-genai/PREINSTALL.md, firestore-multimodal-genai/README.md, firestore-multimodal-genai/extension.yaml, firestore-multimodal-genai/functions/__tests__/google_ai/index.test.ts, firestore-multimodal-genai/functions/__tests__/jest.setup.ts, firestore-multimodal-genai/functions/__tests__/tsconfig.json, firestore-multimodal-genai/functions/__tests__/vertex_ai/index.test.ts, firestore-multimodal-genai/functions/jest.config.js, firestore-multimodal-genai/functions/package-lock.json, firestore-multimodal-genai/functions/src/__mocks__/config.ts, firestore-multimodal-genai/functions/src/config.ts, firestore-multimodal-genai/functions/src/custom_hook.test.ts, firestore-multimodal-genai/functions/src/custom_hook.ts, firestore-multimodal-genai/functions/src/index.ts, firestore-multimodal-genai/functions/src/utils.test.ts, firestore-multimodal-genai/functions/src/utils.ts, storage-reverse-image-search/functions/__tests__/functions/create_index_trigger.test.ts
This PR adds a custom hook feature to the gemini tasks extension
=> feat(firestore-multimodal-genai): add custom hook params

firestore-multimodal-genai/POSTINSTALL.md, firestore-multimodal-genai/PREINSTALL.md, firestore-multimodal-genai/README.md, firestore-multimodal-genai/extension.yaml
This PR updates docs to abide by the latest branding of the models.
=> docs(firestore-multimodal-genai): update docs

firestore-genai-chatbot/README.md, firestore-genai-chatbot/extension.yaml, firestore-genai-chatbot/functions/__tests__/google_ai/index.test.ts, firestore-genai-chatbot/functions/__tests__/util.ts, firestore-genai-chatbot/functions/src/config.ts, firestore-genai-chatbot/functions/src/generate_chat_response.ts, firestore-genai-chatbot/functions/src/generative-client/google_ai.ts, firestore-genai-chatbot/functions/src/generative-client/vertex_ai.ts, firestore-genai-chatbot/functions/src/index.ts, firestore-genai-chatbot/functions/src/types.ts, firestore-multimodal-genai/README.md, firestore-multimodal-genai/extension.yaml, firestore-multimodal-genai/functions/src/config.ts, firestore-multimodal-genai/functions/src/generative-client/generative_ai.ts, firestore-multimodal-genai/functions/src/generative-client/index.ts, firestore-multimodal-genai/functions/src/generative-client/vertex_ai.ts, firestore-multimodal-genai/functions/src/index.ts
This PR adds safety params into the gemini extensions
=> feat(*): add safety setting params

firestore-genai-chatbot/PREINSTALL.md, firestore-genai-chatbot/README.md, firestore-genai-chatbot/extension.yaml, firestore-genai-chatbot/functions/src/config.ts, firestore-multimodal-genai/POSTINSTALL.md, firestore-multimodal-genai/PREINSTALL.md, firestore-multimodal-genai/README.md, firestore-multimodal-genai/extension.yaml, firestore-multimodal-genai/functions/src/config.ts, firestore-multimodal-genai/functions/src/generative-client/generative_ai.ts, firestore-multimodal-genai/functions/src/generative-client/index.ts, firestore-multimodal-genai/functions/src/generative-client/vertex_ai.ts, firestore-multimodal-genai/functions/src/index.ts
This PR changes the model params to a simple string, to make maintenance easier with all the models being released.
There are also some docs changes.
=> feat: change model to string param

firestore-genai-chatbot/CHANGELOG.md, firestore-genai-chatbot/README.md, firestore-genai-chatbot/extension.yaml, firestore-genai-chatbot/functions/package.json, firestore-multimodal-genai/CHANGELOG.md, firestore-multimodal-genai/README.md, firestore-multimodal-genai/extension.yaml, firestore-multimodal-genai/functions/package.json
This PR updates the changelogs and adds publish scripts
=> chore(*): update changelogs

firestore-genai-chatbot/CHANGELOG.md, firestore-genai-chatbot/PREINSTALL.md, firestore-genai-chatbot/README.md, firestore-genai-chatbot/extension.yaml, firestore-multimodal-genai/CHANGELOG.md, firestore-multimodal-genai/PREINSTALL.md, firestore-multimodal-genai/README.md, firestore-multimodal-genai/extension.yaml
fixes https://github.com/GoogleCloudPlatform/firebase-extensions/issues/380
=> docs(*): add gemini docs on regions

firestore-semantic-search/functions/__tests__/types/query.test.ts, firestore-semantic-search/functions/__tests__/vertex/index.test.ts, firestore-semantic-search/functions/src/common/vertex.ts, firestore-semantic-search/functions/src/types/query.ts
=> fix(firestore-semantic-search): neighbor_count parameter location

firestore-vector-search/CHANGELOG.md, firestore-vector-search/functions/package-lock.json, firestore-vector-search/functions/package.json, firestore-vector-search/functions/src/index.ts
fixes https://github.com/GoogleCloudPlatform/firebase-extensions/issues/451
=> fix: correct typos in errors

firestore-multimodal-genai/CHANGELOG.md, firestore-multimodal-genai/functions/src/generative-client/generative_language.ts, firestore-vector-search/CHANGELOG.md, firestore-vector-search/POSTINSTALL.md, firestore-vector-search/extension.yaml, firestore-vector-search/functions/src/queries/query_on_call.ts, firestore-vector-search/functions/src/queries/setup.ts
This PR is for releasing firestore-vector-search
=> release 18/04/24

firestore-genai-chatbot/CHANGELOG.md, firestore-genai-chatbot/functions/__tests__/google_ai/index.test.ts, firestore-genai-chatbot/functions/__tests__/vertex_ai/index.test.ts, firestore-genai-chatbot/functions/package-lock.json, firestore-genai-chatbot/functions/package.json, firestore-genai-chatbot/functions/src/generative-client/vertex_ai.ts
This PR bumps SDK versions and dependencies with vulnerabilities
=> fix(firestore-genai-chatbot): fix vulnerabilities and bump deps

firestore-vector-search/CHANGELOG.md, firestore-vector-search/POSTINSTALL.md, firestore-vector-search/README.md, firestore-vector-search/extension.yaml, firestore-vector-search/functions/src/config.ts
should close https://github.com/GoogleCloudPlatform/firebase-extensions/issues/502
=> fix(firestore-vector-search): correct dimension of Vertex AI gemini, update docs

firestore-vector-search/CHANGELOG.md, firestore-vector-search/extension.yaml, firestore-vector-search/functions/package-lock.json, firestore-vector-search/functions/package.json
This PR should resolve https://github.com/GoogleCloudPlatform/firebase-extensions/issues/523
=> fix: bump deps, fix backfill

.github/workflows/test.yaml
This PR updates the CI, to unblock new fixes
=> test(*): update CI

lerna.json
These are deprecated, no need to run tests etc.
=> chore(*): remove deprecated extensions from lerna

firestore-genai-chatbot/CHANGELOG.md, firestore-genai-chatbot/extension.yaml, firestore-genai-chatbot/functions/package-lock.json, firestore-genai-chatbot/functions/package.json, firestore-genai-chatbot/functions/src/generative-client/genkit.ts
This PR:
- bumps node runtimes in the function(s)
- runs npm audit fix
- bumps genkit dependencies
- adds support for the 2.0 generation of Gemini models
=> feat(firestore-genai-chatbot): bump dependencies, fix vulnerabilities, support 2.0

firestore-vector-search/CHANGELOG.md, firestore-vector-search/extension.yaml, firestore-vector-search/functions/package-lock.json, firestore-vector-search/functions/package.json, lerna.json
Resolves https://github.com/GoogleCloudPlatform/firebase-extensions/issues/618
=> feat(firestore-vector-search): bump node runtime, npm audit

speech-to-text/CHANGELOG.md, speech-to-text/extension.yaml, speech-to-text/functions/package-lock.json, speech-to-text/functions/package.json
=> feat(speech-to-text): bump node runtime, npm audit

firestore-genai-chatbot/functions/package-lock.json, firestore-genai-chatbot/functions/src/generative-client/genkit.ts
fixes https://github.com/GoogleCloudPlatform/firebase-extensions/issues/647
=> feat(firestore-genai-chatbot): add gemini20FlashLite

storage-label-images/CHANGELOG.md, storage-label-images/extension.yaml, storage-label-images/functions/package-lock.json, storage-label-images/functions/package.json
=> feat(storage-label-images): bump node runtime, npm audit

storage-extract-image-text/CHANGELOG.md, storage-extract-image-text/README.md, storage-extract-image-text/extension.yaml, storage-extract-image-text/functions/package-lock.json, storage-extract-image-text/functions/package.json
=> feat(storage-extract-image-text): bump node runtime, npm audit

firestore-genai-chatbot/CHANGELOG.md, firestore-genai-chatbot/PREINSTALL.md, firestore-genai-chatbot/README.md, firestore-genai-chatbot/extension.yaml, firestore-genai-chatbot/functions/__tests__/unit/config.test.ts, firestore-genai-chatbot/functions/__tests__/unit/logger.test.ts, firestore-genai-chatbot/functions/package-lock.json, firestore-genai-chatbot/functions/package.json, firestore-genai-chatbot/functions/src/config.ts, firestore-genai-chatbot/functions/src/generative-client/genkit.ts, firestore-genai-chatbot/functions/src/generative-client/google_ai.ts, firestore-genai-chatbot/functions/src/generative-client/vertex_ai.ts, firestore-genai-chatbot/functions/src/logger.ts, firestore-genai-chatbot/functions/src/logs.ts, firestore-genai-chatbot/functions/src/overrides.ts
fixes https://github.com/GoogleCloudPlatform/firebase-extensions/issues/663
=> feat(firestore-genai-chatbot): add Genkit AI monitoring

firestore-multimodal-genai/CHANGELOG.md, firestore-multimodal-genai/README.md, firestore-multimodal-genai/extension.yaml, firestore-multimodal-genai/functions/__tests__/genkit/client.test.ts, firestore-multimodal-genai/functions/jest.config.json, firestore-multimodal-genai/functions/package-lock.json, firestore-multimodal-genai/functions/package.json, firestore-multimodal-genai/functions/src/config.ts, firestore-multimodal-genai/functions/src/generative-client/genkit.ts
This PR adds Genkit AI Monitoring to firestore-multimodal-genai extension.
Fixes #668
=> feat(firestore-multimodal-genai): Add Genkit AI Monitoring

firestore-genai-chatbot/PREINSTALL.md, firestore-genai-chatbot/README.md
Fixes https://github.com/firebase/extensions/issues/2461
=> docs(firestore-genai-chatbot): add genkit.dev reference to docs

bigquery-firestore-export/functions/package.json, firestore-incremental-capture/functions/package.json, firestore-palm-chatbot/functions/package.json, firestore-palm-gen-text/functions/package.json, firestore-palm-summarize-text/functions/package.json, firestore-semantic-search/functions/package.json, firestore-vector-search/functions/package.json, speech-to-text/functions/package.json, storage-extract-image-text/functions/package.json, storage-label-images/functions/package.json, storage-label-videos/functions/package.json, storage-reverse-image-search/functions/package.json, text-to-speech/functions/package.json
this PR adds publish scripts where they're missing
=> chore(*): add publish scripts

firestore-genai-chatbot/CHANGELOG.md, firestore-genai-chatbot/README.md, firestore-genai-chatbot/extension.yaml, firestore-genai-chatbot/functions/package-lock.json, firestore-genai-chatbot/functions/package.json, firestore-genai-chatbot/functions/src/generative-client/genkit.ts
Resolves https://github.com/GoogleCloudPlatform/firebase-extensions/issues/737
=> feat(firestore-genai-chatbot): add Gemini 2.5 Flash Lite

speech-to-text/functions/package-lock.json
This PR fixes a critical dependency vulnerability
=> chore(speech-to-text): run npm audit fix
