GoogleCloudPlatform/firebase-extensions

- firestore-semantic-search/extension.yaml
> fix(firestore-semantic-search): validation regex for `fields`

- firestore-palm-chatbot/functions/src/discussion.ts
- firestore-palm-chatbot/functions/src/index.ts
- firestore-palm-chatbot/functions/src/logs.ts
If a user deleted a field on a COMPLETED document, this doc would be included and this would result in an "messages must alternate" error from PaLM.
This PR skips messages without the necessary fields, and emits a warning.
> fix(firestore-palm-chatbot): skip documents which are missing fields

- firestore-palm-gen-text/POSTINSTALL.md
- firestore-palm-gen-text/functions/src/errors.ts
- firestore-palm-gen-text/functions/src/index.ts
This PR adds better error handling by writing the error messages back to Firestore and documenting it in PREINSTALL.
It also documents the model limits, linked to #51
> feat(firstore-palm-gen-text): better error handling & docs

- firestore-semantic-search/CHANGELOG.md
- firestore-semantic-search/functions/src/common/utils.ts
- firestore-semantic-search/functions/src/functions/backfill_trigger.ts
Re-installing an extension instance in a different location complains about an existing bucket in a different location, this PR ensures to delete the bucket it exists.
> fix(firestore-semantic-search): delete backfilling bucket if it exists

- .github/workflows/readmes-updated.yaml
This CI flow was previously failing for fork PRs, as it was trying to check out from the wrong repo. This PR fixes the issue.
> fix: correct readme CI flow

- firestore-palm-summarize-text/CHANGELOG.md
- firestore-palm-summarize-text/README.md
- firestore-palm-summarize-text/extension.yaml
- firestore-palm-summarize-text/functions/src/config.ts
- firestore-palm-summarize-text/functions/src/generator.ts
- firestore-palm-summarize-text/functions/src/index.ts
This PR adds a parameter to change the max output tokens for summarize text, and ups the default
> feat(firestore-palm-summarize-text): add max output tokens param

- firestore-palm-chatbot/functions/src/discussion.ts
This PR fixes https://github.com/GoogleCloudPlatform/firebase-extensions/issues/170
If a single message is too long (or context, or examples) then it will still throw but with a useful message.
Otherwise history is truncated to fit the maximum context window.
> fix(firestore-palm-chatbot): truncate history if big payload

- firestore-palm-gen-text/CHANGELOG.md
- firestore-palm-gen-text/PREINSTALL.md
- firestore-palm-gen-text/README.md
- firestore-palm-gen-text/extension.yaml
This PR updates the description of the new threshold params, adds reference to them in the PREINSTALL, and ups the MAX_CONTENT_LENGTH default to 1024
> docs(firestore-palm-gen-text): update threshold params and docs

- firestore-palm-gen-text/extension.yaml
- firestore-palm-summarize-text/extension.yaml
fixes https://github.com/GoogleCloudPlatform/firebase-extensions/issues/214
Note some content will still be blocked even with BLOCK_NONE set, as there are baseline filters that are not configurable.
> fix(*): fix safety threshold options in PaLM extensions

- firestore-incremental-capture/extension.yaml
`start = Date.now(); 'projects/my-project/databases/my-backup/(default)'.match('^projects/(.*?)+/databases/(.*?)+$'); console.log(Date.now() - start)`
12383ms 
vs
`start = Date.now(); 'projects/my-project/databases/my-backup/(default)'.match('^projects/.+/databases/.+$'); console.log(Date.now() - start)`
0ms
> Simplify BACKUP_INSTANCE_ID validationRegex to make it more efficient

- text-to-speech/functions/src/index.ts
Based on the document on https://extensions.dev/extensions/googlecloud/text-to-speech the audioPath should be saved back to the firestore document
`Writes the path to the Storage object back in the same document.`
This PR should fix it.
> fix(text-to-speech): save file path back to firestore document

- firestore-semantic-search/POSTINSTALL.md
- storage-reverse-image-search/POSTINSTALL.md
Removing unnecessary steps from the following extensions: `firestore-semantic-search`, and `storage-reverse-image-search`.
Also, added a missing step to enable Vertex Audit Logs `storage-reverse-image-search`.
> docs(*): remove rules step

- .github/workflows/readmes-updated.yaml
The generate-readme workflow is failing on version 16. Increase to 18.
> ci: increase node version to 18

- firestore-semantic-search/README.md
- firestore-semantic-search/extension.yaml
- storage-reverse-image-search/README.md
- storage-reverse-image-search/extension.yaml
Closes #293 & closes #295 & closes #297
> chore(*-search): typo in param `ACCELERATOR_TYPE`

- firestore-semantic-search/README.md
- firestore-semantic-search/extension.yaml
- storage-reverse-image-search/README.md
- storage-reverse-image-search/extension.yaml
> chore(*-search): fixes a typo `maxiumum`

- .github/workflows/readmes-updated.yaml
reopening https://github.com/GoogleCloudPlatform/firebase-extensions/pull/342
`save-state` and `set-output` commands used in GitHub Actions are deprecated and [GitHub recommends using environment files](https://github.blog/changelog/2023-07-24-github-actions-update-on-save-state-and-set-output-commands/).
This PR updates the usage of `::set-output` to `"$GITHUB_OUTPUT"`
Instructions for envvar usage from GitHub docs:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter
> ci: Use GITHUB_OUTPUT envvar instead of set-output command

- firestore-semantic-search/extension.yaml
- storage-reverse-image-search/extension.yaml
Fixes #525 in the following extensions:
- firestore-semantic-search
- storage-reverse-image-search
> fix(*): singapore location value

- firestore-genai-chatbot/POSTINSTALL.md
- firestore-genai-chatbot/extension.yaml
- firestore-multimodal-genai/POSTINSTALL.md
- firestore-multimodal-genai/PREINSTALL.md
- firestore-multimodal-genai/README.md
- firestore-multimodal-genai/extension.yaml
Resolves #508.
Update the default value to `gemini-1.0-pro` which supports the latest stable version of Gemini 1.0 Pro on both Google AI and Vertex AI.
> fix: update default model name to `gemini-1.0-pro`

- firestore-genai-chatbot/CHANGELOG.md
- firestore-genai-chatbot/POSTINSTALL.md
- firestore-genai-chatbot/extension.yaml
- firestore-multimodal-genai/CHANGELOG.md
- firestore-multimodal-genai/POSTINSTALL.md
- firestore-multimodal-genai/PREINSTALL.md
- firestore-multimodal-genai/README.md
- firestore-multimodal-genai/extension.yaml
- firestore-semantic-search/CHANGELOG.md
- firestore-semantic-search/extension.yaml
- firestore-vector-search/CHANGELOG.md
- firestore-vector-search/extension.yaml
- firestore-vector-search/functions/package-lock.json
- firestore-vector-search/functions/package.json
- storage-reverse-image-search/CHANGELOG.md
- storage-reverse-image-search/extension.yaml
Resolves https://github.com/GoogleCloudPlatform/firebase-extensions/issues/523
This PR releases some extensions
TODO: ensure that all extensions being released are up to date with extensions.dev before we merge and release these versions.
> Release firestore-vector-search, firestore-genai-chatbot, firestore-multimodel-genai,storage-reverse-image-search,firestore-semantic-search

- firestore-genai-chatbot/CHANGELOG.md
- firestore-genai-chatbot/functions/src/firestore.ts
rebase of https://github.com/GoogleCloudPlatform/firebase-extensions/pull/615
fixes https://github.com/GoogleCloudPlatform/firebase-extensions/issues/504
> fix(firestore-genai-chatbot): fetchHistory should order by asc
